# Polymorphism

### 1.Method overriding 

In [1]:
def add(a,b):
    print(a+b)
def add(a,b,c):
    print(a+b+c)

In [3]:
add(10,20,30)

60


### 2.Operator Overloding 
### Other methods
    1.add
    2.sub
    3.mul
    4.trusdiv
    5.floordiv
    6.mod
    7.pow
### methods
    1.lt(less than)
    2.gt(greater than)
    3.le(less or equal)
    4.ge(greater or equal)
    5.eq(equal to)
    6.ne(not equal to)

In [40]:
class Point:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __str__(self):
        return "x ="+str(self.x)+" y ="+str(self.y)
    def __add__(self,other):
        x=self.x+other.x
        y=self.y+other.y
        return Point(x,y)
    
    def __sub__(self,other):
        x=self.x-other.x
        y=self.y-other.y
        return Point(x,y)
    
    def __mul__(self,other):
        x=self.x*other.x
        y=self.y*other.y
        return Point(x,y)
    
    def __truediv__(self,other):
        x=self.x/other.x
        y=self.y/other.y
        return Point(x,y)
    
    def __floordiv__(self,other):
        x=self.x//other.x
        y=self.y//other.y
        return Point(x,y)
    
    def __mod__(self,other):
        x=self.x%other.x
        y=self.y%other.y
        return Point(x,y)
    
    def __pow__(self,other):
        x=self.x**other.x
        y=self.y**other.y
        return Point(x,y)
    
    def __lt__(self,other):
        if self.x<other.x:
            if self.y<other.y:
                return True
        return False
    
    def __gt__(self,other):
        if self.x>other.x:
            if self.y>other.y:
                return True
        return False
    
    def __le__(self,other):
        if self.x<=other.x:
            if self.y<=other.y:
                return True
        return False
    
    def __ge__(self,other):
        if self.x>=other.x:
            if self.y>=other.y:
                return True
        return False
    
    def __eq__(self,other):
        if self.x==other.x:
            if self.y==other.y:
                return True
        return False
    
    def __ne__(self,other):
        if self.x!=other.x:
            if self.y!=other.y:
                return True
        return False

In [41]:
p1=Point(6,31)
p2=Point(3,4)

In [42]:
p3=p1+p2
p4=p1-p2
p5=p1*p2
p6=p1/p2
p7=p1//p2
p8=p1%p2
p9=p1**p2
p10=p1<p2
p11=p1>p2
p12=p1<=p2
p13=p1>=p2
p14=(p1==p2)
p15=p1!=p2
print(p3)
print(p4)
print(p5)
print(p6)
print(p7)
print(p8)
print(p9)
print(p10)
print(p11)
print(p12)
print(p13)
print(p14)
print(p15)

x =9 y =35
x =3 y =27
x =18 y =124
x =2.0 y =7.75
x =2 y =7
x =0 y =3
x =216 y =923521
False
True
False
True
False
True


### 3.Inheritance 
    1.single inheritance
    2.multiple inheritance
    3.multilevel inheritance
    4.heirarchical inheritance
    5.hybrid inheritance

In [69]:
## 1.single inheritance
class Parent:
    def fun1(self):
        print("Hello Parent")
        
class Child(Parent):
    def fun2(self):
        print("Hello child")

In [70]:
p=Parent()
p.fun1()

Hello Parent


In [71]:
c=Child()
c.fun2()
c.fun1()

Hello child
Hello Parent


In [72]:
## 2.multiple inheritance
class Parent1:
    def fun1(self):
        print("Hello parent1")
class Parent2:
    def fun2(self):
        print("Hello parent2")
class Child(Parent1,Parent2):
    def fun3(self):
        print("Hello child")

In [73]:
p=Parent1()
p.fun1()
p1=Parent2()
p1.fun2()
c=Child()
c.fun3()
c.fun2()
c.fun1()

Hello parent1
Hello parent2
Hello child
Hello parent2
Hello parent1


In [74]:
## 3. multilevel inheritance
class Grantparent:
    def fun1(self):
        print("Hello grantparent")
class Parent(Grantparent):
    def fun2(self):
        print("Hello parent")
class Child(Parent):
    def fun3(self):
        print("Hello child")

In [75]:
g=Grantparent()
g.fun1()
p=Parent()
p.fun1()
p.fun2()
c=Child()
c.fun1()
c.fun2()
c.fun3()

Hello grantparent
Hello grantparent
Hello parent
Hello grantparent
Hello parent
Hello child


In [76]:
## 4.hierarchical inheritance
class Parent:
    def fun1(self):
        print("Hello parent")
        
class Child1(Parent):
    def fun2(self):
        print("Hello Child1")
        
class Child2(Parent):
    def fun3(self):
        print("Hello child2")

In [77]:
p=Parent()
p.fun1()

c1=Child1()
c1.fun1()
c1.fun2()

c2=Child2()
c2.fun1()
c2.fun3()

Hello parent
Hello parent
Hello Child1
Hello parent
Hello child2


In [79]:
## hybrid inheritance
class Grantparent:
    def fun1(self):
        print("Hello grantparent")
        
class Parent1(Grantparent):
    def fun2(self):
        print("Hello parent1")
        
class Parent2:
    def fun3(self):
        print("Hello parent2")
        
class Child(Parent1,Parent2):
    def fun4(self):
        print("Hello child")

In [81]:
g=Grantparent()
g.fun1()

p=Parent1()
p.fun1()
p.fun2()

p1=Parent2()
p1.fun3()

c=Child()
c.fun1()
c.fun2()
c.fun3()
c.fun4()

Hello grantparent
Hello grantparent
Hello parent1
Hello parent2
Hello grantparent
Hello parent1
Hello parent2
Hello child


In [84]:
# Practice programm
class Grantparent1:
    def fun1(self):
        print("Hello grantparent1")
class Grantparent2:
    def fun2(self):
        print("Hello grantparent2")

        
class Parent1(Grantparent1,Grantparent2):
    def fun3(self):
        print("Hello parent1")        
class Parent2:
    def fun4(self):
        print("Hello parent2")
class Parent3(Grantparent1,Grantparent2):
    def fun5(self):
        print("Hello parent2")        
        
class Child1(Parent1,Parent2):
    def fun6(self):
        print("Hello child1")
class Child2(Parent3):
    def fun7(self):
        print("Hello child2")

In [85]:
g=Grantparent1()
g.fun1()

g=Grantparent2()
g.fun2()

p=Parent1()
p.fun1()
p.fun2()
p.fun3()

p1=Parent2()
p1.fun4()

p2=Parent3()
p2.fun1()
p2.fun2()
p2.fun5()

c1=Child1()
c1.fun1()
c1.fun2()
c1.fun3()
c1.fun4()
c1.fun6()

c2=Child2()
c2.fun1()
c2.fun2()
c2.fun5()
c2.fun7()

Hello grantparent1
Hello grantparent2
Hello grantparent1
Hello grantparent2
Hello parent1
Hello parent2
Hello grantparent1
Hello grantparent2
Hello parent2
Hello grantparent1
Hello grantparent2
Hello parent1
Hello parent2
Hello child1
Hello grantparent1
Hello grantparent2
Hello parent2
Hello child2


### MRO(Method resolution order) 

In [90]:
# Dimond method
class A:
    def test(self):
        print("in class A")
        
class B(A):
    def test(self):
        print("in class B")
        
class C(A):
    def test(self):
        print("in class C")
        
class D(B,C):
    def display(self):
        print("in class D")

In [91]:
obj=D()
obj.test()

in class B


In [92]:
print(D.__mro__)

(<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>)


In [96]:
class P:
    pass
class Q:
    pass
class R(P,Q):
    pass
class S(Q):
    pass     
class T(S,R):
    pass
a=T()
T.__mro__

(__main__.T, __main__.S, __main__.R, __main__.P, __main__.Q, object)

### Super() Function

In [1]:
class Parent:
    def display(self):
        print("Hello Parent")

class Child(Parent):
    def display(self):
        super().display()
        print("Hello Child")

In [2]:
o=Child()
o.display()

Hello Parent
Hello Child


In [27]:
#pb-633
class Staff:
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
    def display(self):
        print("name =",self.name)
        print("salary =",self.salary)
class Teaching(Staff):
    def __init__(self,name,salary,subject):
        super().__init__(name,salary)
        self.subject=subject
    def display(self):
        super().display()
        print("subject =",self.subject)
class NonTeaching(Staff):
    def __init__(self,name,salary,department):
        super().__init__(name,salary)
        self.department=department
    def display(self):
        super().display()
        print("department =",self.department)    

In [28]:
s1=Staff("Aayushi",80000)
s1.display()

name = Aayushi
salary = 80000


In [29]:
t1=Teaching("Aayushi",80000,"Fcsp-1")
t1.display()

name = Aayushi
salary = 80000
subject = Fcsp-1


In [30]:
n1=NonTeaching("Aayushi",80000,"HR")
n1.display()

name = Aayushi
salary = 80000
department = HR


In [31]:
#pb-642
class Data:
    def __init__(self,value):
        self.value=value
    def __lt__(self,other):
        return self.value<other.value
    
    def __gt__(self,other):
        return self.value>other.value
d1=Data(10)
d2=Data(20)
print(d1<d2)
print(d1>d2)

True
False


In [33]:
# pb-643
class data:
    def __init__(self,value=None):
        if value:
            self.value=value
            self.status=True
        else:
            self.status=False
    def __str__(self):
        return f" status = {self.status}"

In [35]:
d2=data(10)
print(d2)

 status = True


In [36]:
d3=data()
print(d3)

 status = False


In [37]:
# pb-641
class Student:
    def __init__(self,rollNo,name,age,totalMarks):
        self.rollNo=rollNo
        self.name=name
        self.age=age
        self.totalMarks=totalMarks
    def dispaly(self):
        print("name =",self.name)
        print("roll no =",self.rollNo)
        print("age =",self.age)
        print("total marks =",self.totalMarks)
    def __eq__(self,other):
        return self.totalMarks==other.totalMarks

In [42]:
s1=Student(13,"Lucky",20,98.56)
s2=Student(26,"Reyan",20,94.75)
if s1==s2:
    print("s1 and s2 have same marks")
else:
    print(f"{s1.name} and {s2.name} do not have same marks")

Lucky and Reyan do not have same marks


### Abstract class 

In [44]:
from abc import ABC,abstractmethod


In [49]:
class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
        
    @abstractmethod
    def draw(self):
        pass
    
class circle(Shape):
    def __init__(self):
        super().__init__("circle")
    def draw(self):
        print("drawing a circle")
class Triangle(Shape):
    def __init__(self):
        super().__init__("Triangle")
    def draw(self):
        print("drawing a Triangle")

In [50]:
c1=circle()
c1.draw()
t1=Triangle()
t1.draw()

drawing a circle
drawing a Triangle


In [59]:
# pb-657
class Employee(ABC):
    def __init__(self):
        self.id=0
        self.name=""
        self.salary=0
    def get_details(self):
        self.id=int(input("id : "))
        self.name=input("name : ")
        self.salary=int(input("salary : "))
    def display(self):
        print("employee id = ",self.id)
        print("employee name = ",self.name)
        print("employee salary = ",self.salary)
    def return_salary(self):
        return self.salary
    @abstractmethod
    def emp_id(self):
        pass
    
class Perks(Employee):
    def __init__(self):
        super().__init__()
        self.da=0
        self.hra=0
        self.pf=0
    def emp_id(self):
        return self.id
    def calculate(self):
        self.da=self.salary*0.35
        self.hra=self.salary*0.17
        self.pf=self.salary*0.12
    def display_perks(self):
        print(" DA : ",self.da)
        print(" HRA : ",self.hra)
        print(" pf : ",self.pf)
        print(" total perks : ",self.da+self.hra-self.pf)   
        
class NetSalary(Perks):
    def __init__(self):
        super().__init__()
        self.net_salary=0
    def calculate_net_salary(self):
        self.net_salary=self.salary+self.da+self.hra-self.pf
    def display_net(self):
        self.display()
        self.display_perks()
        print("total salary =",self.net_salary)

In [60]:
A=NetSalary()
A.get_details()
A.calculate()
A.calculate_net_salary()
A.display_net()

id : 1
name : john
salary : 25000
employee id =  1
employee name =  john
employee salary =  25000
 DA :  8750.0
 HRA :  4250.0
 pf :  3000.0
 total perks :  10000.0
total salary = 35000.0


# Numpy

#### Creating numpy array

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a=np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### Dimention in Array
    1.0-D array

In [4]:
import numpy as np
a=np.array(42)
print(a)
print(type(a))

42
<class 'numpy.ndarray'>



    2.1-D array

In [5]:
import numpy as np
a=np.array([42,45,49,48,51])
print(a)
print(type(a))

[42 45 49 48 51]
<class 'numpy.ndarray'>



    3.2-D array

In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# 
    4.3-D array

In [9]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(type(a))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


#### check number of dimention 

In [11]:
import numpy as np
a=np.array(42)
b=np.array([42,45,49,48,51])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### higher dimention array 

In [14]:
import numpy as np
A=np.array([1,2,3,4,5],ndmin=5)
print(A)
print(A.ndim)

[[[[[1 2 3 4 5]]]]]
5


#### numpy array slicing
    1-D slicing(positive)

In [15]:
import numpy as np
A=np.array([1,2,3,4,5,6,7])

In [16]:
print(A[4:])

[5 6 7]


In [19]:
print(A[0:6:2])

[1 3 5]


In [20]:
print(A[:2])

[1 2]


# 
    2.1-D slicing(negative)

In [21]:
import numpy as np
A=np.array([1,2,3,4,5,6,7])

In [23]:
print(A[-3:1:-1])

[5 4 3]


In [26]:
print(A[-6:-2])

[2 3 4 5]


# 
    slicing 2-D array

In [27]:
import numpy as np
A=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [28]:
print(A[1,1:4])

[7 8 9]


In [29]:
print(A[:,2])

[3 8]


In [30]:
print(A[:,1:4])

[[2 3 4]
 [7 8 9]]


In [33]:
print(A[::-1,-2:-4:-1])

[[9 8]
 [4 3]]


In [34]:
print(A[:,-3:-1])

[[3 4]
 [8 9]]


    slicing 3-D array

In [35]:
import numpy as np
N=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(N[1,:,2])

[ 9 12]


In [37]:
print(N[:,:,1])

[[ 2  5]
 [ 8 11]]


In [38]:
print(N[:,1,0:2])

[[ 4  5]
 [10 11]]


In [40]:
print(N[:,0,-1:-3:-1])

[[3 2]
 [9 8]]


#### numpy array shape 

In [42]:
import numpy as np
D=np.array([[1,2,3,4],[5,6,7,8],[1,1,1,1]])
print("Shape =",D.shape)

Shape = (3, 4)


In [43]:
D=np.array([[[[[1,2,3,4,5]]]]])
print("Shape =",D.shape)

Shape = (1, 1, 1, 1, 5)


#### numpy array reshaping
    1.case-1 reshape from 1-D to 2-D

In [46]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
S=A.reshape(4,3)
S1=A.reshape(3,4)
S2=A.reshape(6,2)
S3=A.reshape(2,6)
S4=A.reshape(12,1)
print(S)
print(S2)
print(S3)
print(S4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


#### 2.case-2 reshape from 1-D to 3-D 

In [49]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
s=A.reshape(2,6,1)
s1=A.reshape(1,6,2)
s2=A.reshape(2,1,6)
s3=A.reshape(2,2,3)
s4=A.reshape(2,3,2)
s5=A.reshape(3,2,2)
s6=A.reshape(3,4,1)
s6=A.reshape(1,3,4)
print(s)
print(s1)
print(s2)
print(s3)
print(s4)
print(s5)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


#### unknown Dimension 

In [50]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
s1=A.reshape(2,3,-1)
print(s1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
s1=A.reshape(-1,3,2)
print(s1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Flattening  the array

In [52]:
N=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
s=N.reshape(-1)
print(s)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### numpy array iterating
    1.case-1  iterating 1-D array

In [53]:
import numpy as np
arr=np.array([1,2,3])
for i in arr:
    print(i)

1
2
3


# 
    2.case-2  iterating 2-D array

In [55]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


# 
    3.case-3  iterating 3-D array

In [56]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


#### numpy joining array
    case-1 concatenating 1-D array

In [57]:
A1=np.array([1,2,3])
A2=np.array([4,5,6])
A3=np.concatenate((A1,A2))
print(A3)

[1 2 3 4 5 6]



    case-2 concatenating 2-D array
    (A) method-1 axis=0

In [59]:
N1=np.array([[1,2],[3,4]])
N2=np.array([[5,6],[7,8]])
N3=np.concatenate((N1,N2),axis=0)
print(N3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]



    case-2 concatenating 2-D array
    (B) method-2 axis=1

In [60]:
N1=np.array([[1,2],[3,4]])
N2=np.array([[5,6],[7,8]])
N3=np.concatenate((N1,N2),axis=1)
print(N3)

[[1 2 5 6]
 [3 4 7 8]]


# 
    case-1 concatenating 3-D array
    method-1 axis=0

In [63]:
a1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a2=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
a3=np.concatenate((a1,a2),axis=0)
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]



    case-1 concatenating 3-D array
    method-2 axis=1

In [64]:
a1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a2=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]
  [19 20 21]
  [22 23 24]]]


 
    case-1 concatenating 3-D array
    method-3 axis=2

In [65]:
a1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a2=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
a3=np.concatenate((a1,a2),axis=2)
print(a3)

[[[ 1  2  3 13 14 15]
  [ 4  5  6 16 17 18]]

 [[ 7  8  9 19 20 21]
  [10 11 12 22 23 24]]]


#### Numpy spliting array 

In [2]:
import numpy as np
A1=np.array([1,2,3,4,5,6])
a=np.array_split(A1,3)
b=np.array_split(A1,4)
print(a)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


#### Splitting 2-D array 

In [3]:
s=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
s1=np.array_split(s,3)
print(s1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [4]:
s=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
s1=np.array_split(s,4)
print(s1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [5]:
s=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
s1=np.array_split(s,3,axis=1)
print(s1)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


#### where function

In [7]:
w=np.array([1,2,3,4,5,6,7,4])
x=np.where(w==4)
print(x)

(array([3, 7], dtype=int64),)


In [8]:
w=np.array([1,2,3,4,5,6,7,4])
x=np.where(w%2==1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


#### numpy shorting array 
    shorting 1-D array

In [10]:
r=np.array([3,2,5,6,1,4])
print(np.sort(r))

[1 2 3 4 5 6]


In [12]:
r1=np.array(["b","c","a"])
print(np.sort(r1))

['a' 'b' 'c']


In [14]:
r2=np.array([True,False,True])
print(np.sort(r2))

[False  True  True]


    shortting 2-D array

In [15]:
f=np.array([[3,2,4],[5,0,1]])
print(np.sort(f))

[[2 3 4]
 [0 1 5]]


#### sortting 3-D array 

In [16]:
t1=np.array([[[3,2,4],[5,0,1]],[[3,2,1],[5,3,2]]])
print(np.sort(t1))

[[[2 3 4]
  [0 1 5]]

 [[1 2 3]
  [2 3 5]]]


#### Sortting in desending order

In [17]:
r=np.array([3,2,5,6,1,4])
print(np.sort(r)[::-1])

[6 5 4 3 2 1]


In [18]:
f=np.array([[3,2,4],[5,0,1]])
print(np.sort(f)[:,::-1])

[[4 3 2]
 [5 1 0]]


In [19]:
t1=np.array([[[3,2,4],[5,0,1]],[[3,2,1],[5,3,2]]])
print(np.sort(t1)[:,:,::-1])

[[[4 3 2]
  [5 1 0]]

 [[3 2 1]
  [5 3 2]]]


#### random module

In [20]:
from numpy import random
x=random.randint(100)
print(x)

31


In [30]:
from numpy import random
x=random.rand()
print(x)

0.5557046491531644


In [33]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[68 67 62  0 41]


In [34]:
from numpy import random
x=random.randint(100,size=(3,4))
print(x)

[[42 97 30 41]
 [19 83 20 74]
 [ 5  3 94 47]]


In [35]:
from numpy import random
x=random.rand(5)
print(x)

[0.71910557 0.99016338 0.39900933 0.49490772 0.03872668]


In [36]:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.5210562  0.97490547 0.50709085 0.58990985 0.89715518]
 [0.165117   0.31287978 0.36661246 0.36442675 0.93826234]
 [0.87113295 0.5694433  0.70622261 0.97176616 0.25137979]]


In [43]:
z=random.choice([3,5,7,9],size=(3,5))
print(z)

[[9 9 9 3 7]
 [7 7 3 5 7]
 [7 5 3 7 3]]
